### ISSUE TITLE
build failing: cannot find `@agoric/captp`

### ISSUE THREAD

**Issue by warner** [Agoric/cosmic-workspace#9]
Chris and I did a clean checkout of the current `cosmic-workspace` (commit ec3a90a), followed by `git submodule update --init`, `npm clean-install`, `npm run build`. Then I switched into `cosmic-swingset` and did `make scenario3-setup`, which failed:

```
$ make scenario3-setup 
rm -rf t3
bin/ag-solo init t3 --egresses=none
/home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/upload-contract.js:1
Error: Cannot find module '@agoric/captp'
Require stack:
- /home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/upload-contract.js
- /home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/start.js
- /home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/main.js
- /home/warner/bindmounts/trees/cw/cosmic-swingset/bin/ag-solo
    at Object.<anonymous> (/home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/upload-contract.js:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/upload-contract.js',
    '/home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/start.js',
    '/home/warner/bindmounts/trees/cw/cosmic-swingset/lib/ag-solo/main.js',
    '/home/warner/bindmounts/trees/cw/cosmic-swingset/bin/ag-solo'
  ]
}
Makefile:80: recipe for target 'scenario3-setup' failed
make: *** [scenario3-setup] Error 1
```

I don't know what `@agoric/captp` is, but it looks like something is only partially depending upon it.

**Comment by warner** [comment]
We looked inside `node_modules`, and it did not have a `@agoric/captp`, even though captp is listed in `cosmic-swingset/package.json` and `package-lock.json`. Thinking that maybe `npm install` didn't get run inside `cosmic-swingset`, we tried running that directly (`cd cosmic-swingset && npm install`), and got an even weirder error:

```
$ npm install

> @agoric/cosmic-swingset@0.10.5-dev.0 preinstall /home/warner/bindmounts/trees/cw/cosmic-swingset
> make all

go build -v  -buildmode=c-shared -o lib/libagcosmosdaemon.so lib/agcosmosdaemon.go
runtime/cgo
net
command-line-arguments
test "`uname -s 2>/dev/null`" != Darwin || install_name_tool -id `pwd`/lib/libagcosmosdaemon.so lib/libagcosmosdaemon.so
go install -v  -tags " ledger" ./cmd/ag-cosmos-helper
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/warner/.npm/_logs/2019-10-15T22_20_55_557Z-debug.log
```

The full contents of that debug.log are:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/warner/.nvm/versions/node/v12.11.1/bin/node',
1 verbose cli   '/home/warner/.nvm/versions/node/v12.11.1/bin/npm',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.11.1
4 verbose npm-session 7caef1ea1514d0e6
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall @agoric/cosmic-swingset@0.10.5-dev.0
7 info lifecycle @agoric/cosmic-swingset@0.10.5-dev.0~preinstall: @agoric/cosmic-swingset@0.10.5-dev.0
8 verbose lifecycle @agoric/cosmic-swingset@0.10.5-dev.0~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle @agoric/cosmic-swingset@0.10.5-dev.0~preinstall: PATH: /home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/warner/bindmounts/trees/cw/cosmic-swingset/node_modules/.bin:/home/warner/.cargo/bin:/home/warner/.local/bin:/home/warner/.nvm/versions/node/v12.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/warner/go/bin
10 verbose lifecycle @agoric/cosmic-swingset@0.10.5-dev.0~preinstall: CWD: /home/warner/bindmounts/trees/cw/cosmic-swingset
11 silly lifecycle @agoric/cosmic-swingset@0.10.5-dev.0~preinstall: Args: [ '-c', 'make all' ]
12 silly lifecycle @agoric/cosmic-swingset@0.10.5-dev.0~preinstall: Returned: code: 0  signal: null
13 silly install loadCurrentTree
14 silly install readLocalPackageData
15 verbose stack RangeError: Maximum call stack size exceeded
15 verbose stack     at /home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/aproba/index.js:39:16
15 verbose stack     at Array.forEach (<anonymous>)
15 verbose stack     at validate (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/aproba/index.js:34:11)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
15 verbose stack     at flatNameFromTree (/home/warner/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
16 verbose cwd /home/warner/bindmounts/trees/cw/cosmic-swingset
17 verbose Linux 4.9.0-11-amd64
18 verbose argv "/home/warner/.nvm/versions/node/v12.11.1/bin/node" "/home/warner/.nvm/versions/node/v12.11.1/bin/npm" "install"
19 verbose node v12.11.1
20 verbose npm  v6.11.3
21 error Maximum call stack size exceeded
22 verbose exit [ 1, true ]

```

**Comment by warner** [comment]
We repeated these steps with the previous commit (`v1.15.5`) and everything seemed to work, so I think it has something to do with the new `captp` requirement.

**Comment by michaelfig** [comment]
I've fixed the captp issue: I forgot to push my changes after fixing it earlier today.  Please give it another go, if you can, and report back here (or close the issue).

As an educational point, cosmic-workspace symlinks `*/node_modules` to `./node_modules`.  The `npm clean-install` at the top of the tree is the only one that actually downloads any packages, which it does from `./package.json`.  That mysterious `Maximum call stack size exceeded` is because `npm` running in a submodule gets confused by the symlinks.

It should only be necessary to run `npm` in a submodule when updating dependencies, and to do that, you can just blow away the `subdir/node_modules` link.  To get it back, do `npm ci` at the top of the tree.

Anyway, I should make this more transparent!  Going to yarn would be one way of doing that, but I'm pleased with just how fast the development cycle is (compared to separate node_modules folders).
Another option is `lerna`, if we don't want to force others to commit to yarn.
